name: gwb-dc

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - ipywidgets>=0.6.0
  - requests
  - mkl
  - dask
  - zarr
  - sparse
  - discretize
  - simpeg>=0.14.0
  - pip:
    - empymod
